### PR TITLE
MEVO+ handling invalid values for some optional ROIs. 

### PR DESCRIPTION
**Pull request by wonder99**
This is intended to address #138 #141 
Correction to the uneekor must_not_be_zero list.

### CODE REVIEW

**Comment by wonder99** [comment]
@springbok Something funny happened with my commit.  There should be a line setting result to zero, like this
image

**Comment by wonder99** [comment]
You should probably ask the 2 MEVO+ users to beta test this (git issues are linked to this PR)

**Comment by springbok** [comment]
Not sure what went wrong, merged your last pull request Saturday (from memory), didn't see that change when I looked at the changes. I've merged this pull request.

**Comment by wonder99** [comment]
Ya it's all good.  I was just reading the pull request wrong.  It's all
there, thanks
- Paul

**Pull request merged**
